# Generated by Django 5.2.9 on 2025-12-11 14:03

import functools

from django.db import migrations, models

import sgbo_notebook_api.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of this notebook",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "desctipion",
                    models.TextField(
                        blank=True,
                        help_text="Description, which can be in any format you like",
                        verbose_name="Description",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="The body of the notebook as plain text",
                        verbose_name="Notebook Body",
                    ),
                ),
                (
                    "prio",
                    models.CharField(
                        choices=[
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("P3", "P3"),
                            ("P4", "P4"),
                            ("P5", "P5"),
                        ],
                        default="P1",
                        max_length=255,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        choices=[
                            ("112", "112"),
                            ("0900-8844", "0900-8844"),
                            ("Misdaad Anoniem", "Misdaad Anoniem"),
                            ("Social Media", "Social Media"),
                        ],
                        default="112",
                        max_length=255,
                    ),
                ),
                ("source_date", models.DateField(verbose_name="source date")),
                (
                    "entities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A JSON Field representing entities",
                        validators=[
                            functools.partial(
                                sgbo_notebook_api.models.validate_json_data_with_schema,
                                *(),
                                **{
                                    "schema": {
                                        "items": {
                                            "additionalProperties": False,
                                            "properties": {
                                                "end_char": {"type": "integer"},
                                                "label": {"type": "string"},
                                                "start_char": {"type": "integer"},
                                                "text": {"type": "string"},
                                            },
                                            "required": [
                                                "text",
                                                "start_char",
                                                "end_char",
                                                "label",
                                            ],
                                            "type": "object",
                                        },
                                        "type": "array",
                                    }
                                },
                            )
                        ],
                        verbose_name="Entities",
                    ),
                ),
                (
                    "extra",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A JSON Field with extra data to store",
                        verbose_name="Extra data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notebook",
                "verbose_name_plural": "Notebooks",
                "ordering": ("-created",),
            },
        ),
    ]
