# Generated by Django 5.2.9 on 2025-12-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgbo_notebook_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='desctipion',
            new_name='description',
        ),
    ]
